# Generated by Django 4.1 on 2025-12-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('franchise_model', models.CharField(choices=[('SMRA', 'SMRA'), ('MRA', 'MRA'), ('RA', 'RA'), ('User', 'User')], max_length=10)),
                ('company_support_id', models.CharField(max_length=20)),
                ('referral_id', models.CharField(max_length=20, unique=True)),
                ('referral_prefix', models.CharField(max_length=10)),
                ('referral_sequence', models.IntegerField()),
                ('franchise_type', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=5)),
                ('franchise_name', models.CharField(max_length=100)),
                ('holder_name', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('agent_id', models.CharField(max_length=50)),
                ('commission_slab', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('access', models.CharField(default='Blocked', max_length=20)),
                ('created_by', models.BigIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.franchise')),
            ],
            options={
                'db_table': 'franchise',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.franchise')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='FranchiseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'AADHAAR'), ('PAN', 'PAN'), ('PAYMENT', 'PAYMENT'), ('BANK', 'BANK'), ('Agreement', 'Agreement')], max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.franchise')),
            ],
            options={
                'db_table': 'franchise_documents',
            },
        ),
        migrations.CreateModel(
            name='FranchiseBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('branch_name', models.CharField(max_length=100)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.franchise')),
            ],
            options={
                'db_table': 'franchise_bank_details',
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slab', models.DecimalField(decimal_places=2, max_digits=5)),
                ('from_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_from', to='users.franchise')),
                ('to_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_to', to='users.franchise')),
            ],
            options={
                'db_table': 'commissions',
            },
        ),
    ]
