# Generated by Django 4.1 on 2025-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='franchisedocuments',
            name='doc_type',
            field=models.CharField(choices=[('AADHAAR', 'AADHAAR'), ('PAN', 'PAN'), ('PAYMENT', 'PAYMENT'), ('AGREEMENT', 'AGREEMENT'), ('BANK_CHEQUE', 'Cancelled Cheque'), ('BANK_PASSBOOK', 'Passbook'), ('BANK_STATEMENT', 'Bank Statement')], max_length=20),
        ),
    ]
