# Generated by Django 4.1 on 2025-12-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_franchise_status_alter_franchisedocuments_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.franchise'),
        ),
    ]
