# Generated by Django 4.1 on 2025-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_franchise_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='status_date',
            field=models.DateTimeField(null=True),
        ),
    ]
