# Generated by Django 4.1.13 on 2026-07-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_franchise_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='referral_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='referral_prefix',
            field=models.CharField(max_length=64),
        ),
    ]
