# Generated by Django 4.1 on 2025-02-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('aadhaar_front_image', models.CharField(default='', max_length=300)),
                ('aadhaar_back_image', models.CharField(default='', max_length=300)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('pan_front_image', models.CharField(default='', max_length=300)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('password_text', models.CharField(default='', max_length=200)),
                ('referral_code', models.CharField(default='', max_length=200)),
                ('access', models.CharField(default='Granted', max_length=20)),
                ('token_logged_user', models.CharField(default='', max_length=100)),
                ('unique_application_id', models.CharField(default='', max_length=300, null=True)),
                ('app_id_date', models.DateTimeField(null=True)),
                ('device_details', models.BinaryField(null=True)),
                ('fcm_registered_id', models.CharField(default='', max_length=300, null=True)),
                ('fcm_date', models.DateTimeField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.BinaryField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('request_date_time', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('password_changed', models.CharField(default='No', max_length=10)),
                ('changed_date_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('unique_id', models.CharField(default='', max_length=300, unique=True)),
                ('token_logged_user', models.CharField(default='', max_length=100)),
                ('customer', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.customer', to_field='unique_id')),
            ],
            options={
                'db_table': 'customer_password_reset_request',
            },
        ),
        migrations.CreateModel(
            name='CustomerLoginReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('login_date_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.BinaryField()),
                ('token_logged_user', models.CharField(default='', max_length=100)),
                ('customer', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.customer', to_field='unique_id')),
            ],
            options={
                'db_table': 'customer_login_report',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('postoffice', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('address_line_1', models.CharField(default='', max_length=255)),
                ('address_line_2', models.CharField(default='', max_length=255)),
                ('access', models.CharField(default='Granted', max_length=20)),
                ('token_logged_user', models.CharField(default='', max_length=100)),
                ('customer', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.customer', to_field='unique_id')),
            ],
            options={
                'db_table': 'customer_address',
            },
        ),
    ]
