# Generated by Django 4.1 on 2025-02-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mac_reset_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='MacResetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('old_unique_application_id', models.CharField(default='', max_length=300, null=True)),
                ('old_app_id_date', models.DateTimeField()),
                ('device_details', models.BinaryField(null=True)),
                ('added_by', models.CharField(default='', max_length=50)),
                ('customer', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.customer', to_field='unique_id')),
            ],
            options={
                'db_table': 'customer_mac_reset_details',
            },
        ),
    ]
