# Generated by Django 4.1 on 2026-01-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_mac_reset_count_macresetdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trading',
            field=models.CharField(default='OFF', max_length=5),
        ),
    ]
