# Generated by Django 4.2.28 on 2026-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='link_status',
            field=models.CharField(default='Unused', max_length=20),
        ),
    ]
