# Generated by Django 4.2.28 on 2026-04-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_passwordresetrequest_link_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('old_referral_code', models.CharField(max_length=50)),
                ('new_referral_code', models.CharField(max_length=50)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason_for_transfer', models.TextField(blank=True, null=True)),
                ('transfer_by', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'referral_history',
            },
        ),
    ]
