# Generated by Django 6.0.6 on 2026-07-05 10:39

from django.db import migrations
from datetime import timedelta

def adjust_customer_registration_times(apps, schema_editor):
    Customer = apps.get_model('customer', 'Customer')
    for customer in Customer.objects.all():
        if customer.date:
            customer.date = customer.date - timedelta(hours=5, minutes=30)
            customer.save(update_fields=['date'])

    CustomerLoginReport = apps.get_model('customer', 'CustomerLoginReport')
    for report in CustomerLoginReport.objects.all():
        if report.login_date_time:
            report.login_date_time = report.login_date_time - timedelta(hours=5, minutes=30)
            report.save(update_fields=['login_date_time'])

class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_aadhaar_back_image_and_more'),
    ]

    operations = [
        migrations.RunPython(adjust_customer_registration_times),
    ]
