# Generated by Django 4.1 on 2025-02-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('name', models.CharField(default='', max_length=500, unique=True)),
                ('image', models.CharField(max_length=700)),
                ('access', models.CharField(default='Blocked', max_length=20)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GenderCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('gender_name', models.CharField(default='', max_length=100, unique=True)),
                ('access', models.CharField(default='Blocked', max_length=20)),
            ],
            options={
                'db_table': 'gender_categories',
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('metal_name', models.CharField(default='', max_length=100, unique=True)),
                ('access', models.CharField(default='Blocked', max_length=20)),
            ],
            options={
                'db_table': 'metal',
            },
        ),
        migrations.CreateModel(
            name='MetalPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('purity', models.CharField(default='', max_length=100)),
                ('access', models.CharField(default='Blocked', max_length=20)),
                ('metal', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.metal', to_field='unique_id')),
            ],
            options={
                'db_table': 'metal_purity',
            },
        ),
        migrations.CreateModel(
            name='MetalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('type', models.CharField(default='', max_length=100)),
                ('access', models.CharField(default='Blocked', max_length=20)),
                ('metal', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.metal', to_field='unique_id')),
            ],
            options={
                'db_table': 'metal_type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('name', models.CharField(default='', max_length=500, unique=True)),
                ('size', models.CharField(default='', max_length=100)),
                ('access', models.CharField(default='Blocked', max_length=20)),
                ('hot_sale', models.CharField(default='No', max_length=20)),
                ('description', models.BinaryField()),
                ('category_description', models.BinaryField()),
                ('price_per_10_gm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('weight_in_gm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gst_in_percent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('making_fixed', models.CharField(default='No', max_length=20)),
                ('making_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('delivery_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('discount_in_percent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.category', to_field='unique_id')),
                ('metal', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.metal', to_field='unique_id')),
                ('metal_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.metaltype', to_field='unique_id')),
                ('purity', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.metalpurity', to_field='unique_id')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('unit_name', models.CharField(default='', max_length=100, unique=True)),
                ('access', models.CharField(default='Blocked', max_length=20)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Product_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('video_url', models.CharField(default='', max_length=300)),
                ('added_by', models.CharField(default='', max_length=50)),
                ('product', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.product', to_field='unique_id')),
            ],
            options={
                'db_table': 'product_videos',
            },
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('image_url', models.CharField(default='', max_length=300)),
                ('image_type', models.CharField(default='', max_length=50)),
                ('added_by', models.CharField(default='', max_length=50)),
                ('product', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.product', to_field='unique_id')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='MetalPurityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('price_per_10_gm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('access', models.CharField(default='Blocked', max_length=20)),
                ('metal', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.metal', to_field='unique_id')),
                ('purity', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.metalpurity', to_field='unique_id')),
            ],
            options={
                'db_table': 'metal_purity_price',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='gender_categories',
            field=models.ManyToManyField(related_name='categories', to='product.gendercategories'),
        ),
        migrations.AddConstraint(
            model_name='metaltype',
            constraint=models.UniqueConstraint(fields=('type', 'metal'), name='unique_metal_type'),
        ),
        migrations.AddConstraint(
            model_name='metalpurityprice',
            constraint=models.UniqueConstraint(fields=('purity', 'metal'), name='unique_metal_purity_price'),
        ),
        migrations.AddConstraint(
            model_name='metalpurity',
            constraint=models.UniqueConstraint(fields=('purity', 'metal'), name='unique_metal_purity'),
        ),
    ]
