# Generated by Django 4.1 on 2025-03-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_stockmovement_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
