# Generated by Django 4.2.28 on 2026-03-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='date',
        ),
    ]
