# Generated by Django 4.1 on 2025-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('image_type', models.CharField(default='', max_length=30)),
                ('sequence', models.IntegerField()),
                ('image', models.CharField(default='', max_length=500)),
                ('access', models.CharField(default='', max_length=20)),
                ('added_by', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'image_slider',
            },
        ),
    ]
