# Generated by Django 6.0.6 on 2026-06-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0003_companybankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=83.0, max_digits=10),
        ),
    ]
