# Generated by Django 6.0.6 on 2026-06-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0004_companybankdetails_dollar_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='spread',
            field=models.IntegerField(default=200, help_text='Order spread points applied on gold/silver buy rates'),
        ),
    ]
