# Generated by Django 6.0.6 on 2026-06-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0005_companybankdetails_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='cached_gold_ask',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='cached_gold_bid',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='cached_silver_ask',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='cached_silver_bid',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='last_rates_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='slow_fluctuation',
            field=models.BooleanField(default=False, help_text='Enable slow market rate fluctuations'),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='slow_interval_mins',
            field=models.IntegerField(default=15, help_text='Interval in minutes for slow rate updates'),
        ),
    ]
