# Generated by Django 6.0.6 on 2026-06-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0006_companybankdetails_cached_gold_ask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybankdetails',
            name='cached_gold_ask',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='cached_gold_bid',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='cached_silver_ask',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='cached_silver_bid',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='last_rates_fetched',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='slow_fluctuation',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='slow_interval_mins',
        ),
    ]
