# Generated by Django 6.0.6 on 2026-06-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0007_remove_companybankdetails_cached_gold_ask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='pnl_refresh_interval',
            field=models.IntegerField(default=5, help_text='Live PNL refresh interval in seconds'),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='rate_refresh_interval',
            field=models.IntegerField(default=10, help_text='Live rate refresh interval in seconds'),
        ),
    ]
