# Generated by Django 6.0.6 on 2026-07-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0008_companybankdetails_pnl_refresh_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='base_gold_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Anchor INR/gm gold price used in dynamic scale formula. MUST be set — system will error if blank.', max_digits=12, null=True),
        ),
    ]
