# Generated by Django 6.0.6 on 2026-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0009_companybankdetails_base_gold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='manual_market_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='stop_api_hits',
            field=models.BooleanField(default=False),
        ),
    ]
