# Generated by Django 6.0.6 on 2026-07-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0010_companybankdetails_manual_market_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='bulk_override_gold_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='bulk_override_min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='bulk_override_min_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='bulk_override_silver_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
