# Generated by Django 4.1.13 on 2026-07-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0011_companybankdetails_bulk_override_gold_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='withdrawals_closed',
            field=models.BooleanField(default=False, help_text='Disable withdrawals globally'),
        ),
    ]
