# Generated by Django 4.1.13 on 2026-07-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_misc', '0012_companybankdetails_withdrawals_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='market_closed_message',
            field=models.CharField(blank=True, default='', help_text='Optional message to display in marquee when market is closed', max_length=500),
        ),
    ]
