"""
Django settings for ornament project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import firebase_admin
from firebase_admin import credentials, messaging
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mq^4=&!y^h!^w^9d61y!y#ftczqr_i9kkvq!_pgz&p5ng-^i1f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['127.0.0.1', '187.127.178.97','172.20.10.4', 'localhost', '10.0.2.2', 'goldrushaura.com', 'www.goldrushaura.com']
env_hosts = os.getenv('ALLOWED_HOSTS')
if env_hosts:
    ALLOWED_HOSTS.extend([h.strip() for h in env_hosts.split(',') if h.strip()])

# Firebase Details
# cred = credentials.Certificate("private/goldmines-b96dc-firebase-adminsdk-fbsvc-d8e650662d.json")
FIREBASE_CRED_PATH = os.path.join(BASE_DIR,"private","goldmines-b96dc-firebase-adminsdk-fbsvc-d8e650662d.json")
cred = credentials.Certificate(FIREBASE_CRED_PATH)
firebase_admin.initialize_app(cred)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework.authtoken',
    'messaging_hub.apps.MessagingHubConfig',
    'website.apps.WebsiteConfig',
    'authentication.apps.AuthenticationConfig',
    'utility.apps.UtilityConfig',
    'dashboard.apps.DashboardConfig',
    'product.apps.ProductConfig',
    'portal_misc.apps.PortalMiscConfig',
    'customer_reports.apps.CustomerReportsConfig',
    'users.apps.UsersConfig',
    'customer.apps.CustomerConfig',
    'customer_product.apps.CustomerProductConfig',
    'customer_order.apps.CustomerOrderConfig',
    'app_misc.apps.AppMiscConfig',
    'customer_trading.apps.CustomerTradingConfig',
    'customer_wallet.apps.CustomerWalletConfig',
    'customer_transaction.apps.CustomerTransactionConfig',
    'customer_authentication.apps.CustomerAuthenticationConfig',
    'portal_users.apps.PortalUsersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Start custom middleware
    'utility.middleware.check_access_middleware.CheckAccessMiddleware',
    # End custom middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # JWT AUTH Middleware
    'customer_trading.middleware.trading_auth_middleware.TradingAuthMiddleware',
    # JWT AUTH Middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ornament.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Start custom template
                'utility.context_processors.sidebar_context',
                'utility.context_processors.settings_context',
                # End custom template
            ],
        },
    },
]

WSGI_APPLICATION = 'ornament.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'ohwqiijn_gold_mine'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True  # Enables timezone support


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

#STATIC_URL = 'static/'
#MEDIA_URL = 'media/'

STATICFILES_DIRS=[os.path.join(BASE_DIR, 'static'),]

# if DEBUG == True:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
#     MEDIA_ROOT = os.path.join(BASE_DIR,'media')
# else:
#STATIC_ROOT = '/directorylink/static'
#MEDIA_ROOT = '/directorylink/media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # ✅ Add first
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}

# REDIS_HOST = "127.0.0.1"
# REDIS_PORT = 6379
# REDIS_DB = 0
OTT_TTL_SECONDS = 30
PIN_TTL_SECONDS = 600  # 10 minutes
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1", # Database 1 for OTT
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'trading_cache',
    }
}
# python manage.py createcachetable trading_cache

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG        # True in production (HTTPS), False in local development (HTTP)
CSRF_COOKIE_SAMESITE = "Strict"

DOMAIN_NAME = 'https://goldrushaura.com/'
DOMAIN_NAME_DI = 'https://goldrushaura.com/digital-investment/'
DOMAIN_NAME_PORTAL = 'https://goldrushaura.com/portal/'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

RAZORPAY_KEY_ID = "rzp_live_SWYkvLQAZBvUO0"
RAZORPAY_KEY_SECRET = "Y7WzMRFYpD60MKccks82q7Tx"

METAL_API_KEY = "2Ehlo6aoBuvDpF07LHgs00UMHz3jyq8NP4Yryuk0QD9IxVpzsOy1tDj2EtYZ"

# Market spread applied on top of live buy rate when customer places an order
ORDER_SPREAD_POINTS = 200

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
