# Generated by Django 4.1 on 2025-02-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(default='', max_length=200)),
                ('mobile_number', models.CharField(default='', max_length=10, unique=True)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('password_text', models.CharField(default='', max_length=200)),
                ('access', models.CharField(default='', max_length=20)),
                ('added_by', models.CharField(default='', max_length=20)),
                ('table_name', models.CharField(default='', max_length=50)),
                ('table_id', models.CharField(default='', max_length=32)),
                ('profile_img', models.CharField(default='', max_length=300)),
                ('uniqueApplicationID', models.CharField(default='', max_length=500, null=True, unique=True)),
                ('app_id_date', models.DateTimeField(null=True)),
                ('device_details', models.CharField(default='', max_length=300)),
                ('fcm_registered_id', models.CharField(default='', max_length=500, null=True, unique=True)),
                ('fcm_date', models.DateTimeField(null=True)),
                ('mac_reset_count', models.IntegerField()),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Mac_Reset_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('unique_id', models.CharField(default='', max_length=32, unique=True)),
                ('old_uniqueApplicationID', models.CharField(default='', max_length=500)),
                ('old_app_id_date', models.DateTimeField(null=True)),
                ('old_device_details', models.CharField(default='', max_length=300)),
                ('added_by', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'mac_reset_details',
            },
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='User_Activity_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('username', models.CharField(default='', max_length=20)),
                ('page_name', models.CharField(default='', max_length=200)),
                ('message', models.BinaryField()),
                ('login', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.login')),
            ],
            options={
                'db_table': 'user_activity_log',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('request_date_time', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('password_changed', models.CharField(default='No', max_length=10)),
                ('changed_date_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('unique_id', models.CharField(default='', max_length=300, unique=True)),
                ('reset_type', models.CharField(default='', max_length=20)),
                ('login', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.login')),
            ],
            options={
                'db_table': 'password_reset_request',
            },
        ),
        migrations.CreateModel(
            name='LoginReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('login_date_time', models.DateTimeField()),
                ('logout_date_time', models.DateTimeField(null=True)),
                ('login_type', models.CharField(default='', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('login', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.login')),
            ],
            options={
                'db_table': 'login_report',
            },
        ),
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.user_role'),
        ),
    ]
