# Generated by Django 4.1 on 2025-12-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_login_mac_reset_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='fcm_registered_id',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='uniqueApplicationID',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
