# Generated by Django 4.1 on 2025-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_login_fcm_registered_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='profile_img',
            field=models.CharField(default='img/no-image.png', max_length=300),
        ),
    ]
