# Generated by Django 4.2.28 on 2026-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_login_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='link_status',
            field=models.CharField(default='Unused', max_length=20),
        ),
    ]
