# Generated by Django 4.1 on 2025-02-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cart_id', models.CharField(default='', max_length=32, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('cart_status', models.CharField(default='Pending', max_length=20)),
                ('token_logged_user', models.CharField(default='', max_length=100)),
                ('customer', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.customer', to_field='unique_id')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('order_id', models.CharField(default='', max_length=32, unique=True)),
                ('order_number', models.CharField(default='', max_length=32, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('postoffice', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('address_line_1', models.CharField(default='', max_length=255)),
                ('address_line_2', models.CharField(default='', max_length=255)),
                ('total_items', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=4, max_digits=20)),
                ('remark', models.CharField(default='', max_length=50)),
                ('order_status', models.CharField(default='Placed', max_length=20)),
                ('token_logged_user', models.CharField(default='', max_length=100)),
                ('razorpay_order_id', models.CharField(default='', max_length=32, null=True)),
                ('razorpay_payment_id', models.CharField(default='', max_length=32, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('address', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.customeraddress', to_field='unique_id')),
                ('cart', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_order.cart', to_field='cart_id')),
                ('customer', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.customer', to_field='unique_id')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prd_detail_id', models.CharField(default='', max_length=32)),
                ('order_status', models.CharField(max_length=20)),
                ('order', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_order.order', to_field='order_id')),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prd_detail_id', models.CharField(default='', max_length=32, unique=True)),
                ('category_name', models.CharField(default='', max_length=500)),
                ('product_name', models.CharField(default='', max_length=500)),
                ('size', models.CharField(default='', max_length=100)),
                ('description', models.BinaryField()),
                ('category_description', models.BinaryField()),
                ('metal', models.CharField(default='', max_length=100)),
                ('metal_type', models.CharField(default='', max_length=100)),
                ('purity', models.CharField(default='', max_length=100)),
                ('price_per_10_gm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('weight_in_gm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gst_in_percent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('making_fixed', models.CharField(max_length=20)),
                ('making_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('delivery_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('discount_in_percent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total', models.DecimalField(decimal_places=4, max_digits=20)),
                ('order_status', models.CharField(default='Placed', max_length=20)),
                ('category', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.category', to_field='unique_id')),
                ('order', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_order.order', to_field='order_id')),
                ('product', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.product', to_field='unique_id')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category_name', models.CharField(default='', max_length=500)),
                ('product_name', models.CharField(default='', max_length=500)),
                ('size', models.CharField(default='', max_length=100)),
                ('description', models.BinaryField()),
                ('category_description', models.BinaryField()),
                ('metal', models.CharField(default='', max_length=100)),
                ('metal_type', models.CharField(default='', max_length=100)),
                ('purity', models.CharField(default='', max_length=100)),
                ('price_per_10_gm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('weight_in_gm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gst_in_percent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('making_fixed', models.CharField(max_length=20)),
                ('making_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('delivery_charge', models.DecimalField(decimal_places=4, max_digits=20)),
                ('discount_in_percent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cart', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_order.cart', to_field='cart_id')),
                ('category', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.category', to_field='unique_id')),
                ('product', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='product.product', to_field='unique_id')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
    ]
