# Generated by Django 4.1 on 2025-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
