# Generated by Django 4.1 on 2025-03-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0002_order_address_mobile_order_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cart_items', to='customer_order.cart', to_field='cart_id'),
        ),
    ]
