# Generated by Django 4.1 on 2026-01-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_franchise_status_date'),
        ('customer', '0003_customer_trading'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trading_enabled', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approved_by', models.BigIntegerField(null=True)),
                ('approved_date', models.DateTimeField(null=True)),
                ('is_blocked', models.CharField(default='No', max_length=5)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('ra', models.ForeignKey(limit_choices_to={'franchise_model': 'RA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.franchise')),
            ],
            options={
                'db_table': 'customer_trading_account',
            },
        ),
        migrations.CreateModel(
            name='CustomerTradingTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('accepted', models.CharField(default='No', max_length=5)),
                ('accepted_date', models.DateTimeField(null=True)),
                ('accepted_ip', models.CharField(max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'customer_trading_terms',
            },
        ),
        migrations.CreateModel(
            name='CustomerTradingLoginReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('login_ip', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_trading.customertradingaccount')),
            ],
            options={
                'db_table': 'customer_trading_login_report',
            },
        ),
        migrations.CreateModel(
            name='CustomerTradingLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_login_ip', models.CharField(max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'customer_trading_login',
            },
        ),
        migrations.CreateModel(
            name='CustomerTradingDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'AADHAAR'), ('PAN', 'PAN'), ('BANK_CHEQUE', 'Cancelled Cheque'), ('BANK_PASSBOOK', 'Passbook'), ('BANK_STATEMENT', 'Bank Statement')], max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'customer_trading_documents',
            },
        ),
        migrations.CreateModel(
            name='CustomerTradingBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('branch_name', models.CharField(max_length=100)),
                ('verified', models.CharField(default='No', max_length=5)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'customer_trading_bank_details',
            },
        ),
    ]
