# Generated by Django 4.1 on 2026-01-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_trading'),
        ('customer_trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertradingdocuments',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
