# Generated by Django 4.1 on 2026-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_trading', '0002_alter_customertradingdocuments_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertradinglogin',
            name='password_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
