# Generated by Django 4.1 on 2026-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_trading', '0003_customertradinglogin_password_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertradingloginreport',
            name='login_type',
            field=models.CharField(default='Web', max_length=20),
        ),
    ]
