# Generated by Django 4.2.28 on 2026-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_trading', '0004_customertradingloginreport_login_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertradingloginreport',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='customertradinglogin',
            old_name='trading_password',
            new_name='pin_hash',
        ),
        migrations.RenameField(
            model_name='customertradinglogin',
            old_name='salt',
            new_name='pin_salt',
        ),
        migrations.RemoveField(
            model_name='customertradinglogin',
            name='password_text',
        ),
        migrations.RemoveField(
            model_name='customertradingloginreport',
            name='session_id',
        ),
        migrations.AddField(
            model_name='customertradinglogin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customertradinglogin',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertradinglogin',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customertradinglogin',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customertradinglogin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customertradinglogin',
            name='wrong_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customertradingloginreport',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('LOCKED', 'Locked')], default='SUCCESS', max_length=10),
        ),
        migrations.AlterField(
            model_name='customertradinglogin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customertradinglogin',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customertradingloginreport',
            name='login_type',
            field=models.CharField(choices=[('WEB', 'Web'), ('APP', 'App')], default='WEB', max_length=20),
        ),
    ]
