# Generated by Django 4.2.28 on 2026-03-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_trading', '0005_alter_customertradingloginreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertradingaccount',
            name='account_type',
            field=models.CharField(choices=[('LIVE', 'Live'), ('DEMO', 'Demo')], default='DEMO', max_length=10),
        ),
    ]
