# Generated by Django 4.1 on 2026-02-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_wallet', '0002_membershipmaster_service_fee_percent'),
        ('customer', '0003_customer_trading'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('metal_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], default='GOLD', max_length=6)),
                ('quantity_gm', models.PositiveIntegerField()),
                ('metal_rate_per_gm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metal_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profit_loss', models.CharField(blank=True, choices=[('PROFIT', 'Profit'), ('LOSS', 'Loss')], max_length=6, null=True)),
                ('profit_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_loss_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_wallet.membershipmaster')),
                ('parent_buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_transactions', to='customer_transaction.customertransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet.customerwallet')),
            ],
            options={
                'db_table': 'customer_transaction',
            },
        ),
    ]
