# Generated by Django 4.1 on 2026-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='order_type',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('BUYBACK', 'Buyback')], default='BOOKING', max_length=10),
        ),
    ]
