# Generated by Django 4.1 on 2026-02-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0002_customertransaction_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='auto_sell_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto sell trigger value set by user', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='TransactionAutoSellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_auto_sell_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_auto_sell_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('changed_by', models.CharField(default='CUSTOMER', help_text='CUSTOMER / SYSTEM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_sell_history', to='customer_transaction.customertransaction')),
            ],
            options={
                'db_table': 'transaction_auto_sell_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
