# Generated by Django 4.1 on 2026-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0003_customertransaction_auto_sell_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='auto_sell_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
