# Generated by Django 4.1 on 2026-02-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0004_customertransaction_auto_sell_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='sold_via',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto Sell')], default='MANUAL', max_length=10),
        ),
    ]
