# Generated by Django 4.2.28 on 2026-03-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0003_customerdemowallet'),
        ('customer', '0003_customer_trading'),
        ('customer_transaction', '0005_customertransaction_sold_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDemoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('metal_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], default='GOLD', max_length=6)),
                ('order_type', models.CharField(choices=[('BOOKING', 'Booking'), ('BUYBACK', 'Buyback')], default='BOOKING', max_length=10)),
                ('quantity_gm', models.PositiveIntegerField()),
                ('metal_rate_per_gm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metal_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profit_loss', models.CharField(blank=True, choices=[('PROFIT', 'Profit'), ('LOSS', 'Loss')], max_length=6, null=True)),
                ('profit_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_loss_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('auto_sell_enabled', models.BooleanField(default=False)),
                ('auto_sell_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto sell trigger value set by user', max_digits=12, null=True)),
                ('sold_via', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto Sell')], default='MANUAL', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('parent_buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_sell_transactions', to='customer_transaction.customerdemotransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet.customerdemowallet')),
            ],
            options={
                'db_table': 'customer_demo_transaction',
            },
        ),
        migrations.CreateModel(
            name='DemoTransactionAutoSellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_auto_sell_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_auto_sell_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('changed_by', models.CharField(default='CUSTOMER', help_text='CUSTOMER / SYSTEM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_auto_sell_history', to='customer_transaction.customerdemotransaction')),
            ],
            options={
                'db_table': 'demo_transaction_auto_sell_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
