# Generated by Django 4.2.28 on 2026-03-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0004_customerdemowallet_current_membership'),
        ('customer_transaction', '0006_customerdemotransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdemotransaction',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_wallet.membershipmaster'),
        ),
    ]
