# Generated by Django 4.2.28 on 2026-03-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0007_customerdemotransaction_membership'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerdemotransaction',
            index=models.Index(fields=['customer', 'created_at'], name='customer_de_custome_ce1a51_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['customer', 'created_at'], name='customer_tr_custome_cf4872_idx'),
        ),
    ]
