# Generated by Django 6.0.6 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0008_customerdemotransaction_customer_de_custome_ce1a51_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdemotransaction',
            name='auto_closed_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='auto_closed_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerdemotransaction',
            name='sold_via',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto Sell'), ('WEEKLY_AUTO_CLOSE', 'Weekly Auto Close')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='customertransaction',
            name='sold_via',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto Sell'), ('WEEKLY_AUTO_CLOSE', 'Weekly Auto Close')], default='MANUAL', max_length=20),
        ),
    ]
