# Generated by Django 6.0.6 on 2026-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0009_customerdemotransaction_auto_closed_weekly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='admin_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MetalRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=6)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metal_rate_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metal_type', 'created_at'], name='metal_rate__metal_t_1e741c_idx')],
            },
        ),
    ]
