# Generated by Django 4.1.13 on 2026-07-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_transaction', '0010_customertransaction_admin_rate_override_metalratelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalratelog',
            name='source',
            field=models.CharField(choices=[('LIVE', 'Live API'), ('ADMIN_OVERRIDE', 'Admin Override'), ('SPREAD_CHANGE', 'Spread/Rate Change')], default='LIVE', max_length=20),
        ),
    ]
