# Generated by Django 4.1 on 2026-01-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_customer_trading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Normal', 'Normal'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master Gold', 'Master Gold')], max_length=20, unique=True)),
                ('min_amount', models.PositiveIntegerField()),
                ('max_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('service_fee', models.PositiveIntegerField()),
                ('daily_slot', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'membership_master',
            },
        ),
        migrations.CreateModel(
            name='WalletRechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_wallet.membershipmaster')),
            ],
            options={
                'db_table': 'wallet_recharge_order',
            },
        ),
        migrations.CreateModel(
            name='WalletRechargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('membership_allocated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_wallet.membershipmaster')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet.walletrechargeorder')),
            ],
            options={
                'db_table': 'wallet_recharge_history',
            },
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_wallet.membershipmaster')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'customer_wallet',
            },
        ),
    ]
