# Generated by Django 4.1 on 2026-01-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmaster',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
