# Generated by Django 4.2.28 on 2026-03-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_trading'),
        ('customer_wallet', '0002_membershipmaster_service_fee_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDemoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'customer_demo_wallet',
            },
        ),
    ]
