# Generated by Django 4.2.28 on 2026-03-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0003_customerdemowallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdemowallet',
            name='current_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_wallet.membershipmaster'),
        ),
    ]
