# Generated by Django 6.0.6 on 2026-06-09 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_aadhaar_back_image_and_more'),
        ('customer_wallet', '0007_walletmanualcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletManualDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('remark', models.TextField()),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debited_by', models.CharField(max_length=50)),
                ('debited_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'wallet_manual_debit',
                'ordering': ['-debited_on'],
            },
        ),
    ]
