# Generated by Django 6.0.6 on 2026-06-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0008_walletmanualdebit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
