# Generated by Django 6.0.6 on 2026-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0009_withdrawalrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdemowallet',
            name='stop_loss_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Default stop loss percentage for all orders'),
        ),
        migrations.AddField(
            model_name='customerwallet',
            name='stop_loss_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Default stop loss percentage for all orders'),
        ),
    ]
