# Generated by Django 6.0.6 on 2026-07-05 09:29

from django.db import migrations, models

def populate_new_memberships(apps, schema_editor):
    MembershipMaster = apps.get_model('customer_wallet', 'MembershipMaster')
    new_tiers = [
        # Level, min_amount, max_amount, service_fee, service_fee_percent, daily_slot, is_new_plan
        ('Normal', 5000, 99999, 50, 10.00, 8, True),
        ('Vip 1', 100000, None, 48, 9.60, 16, True),
        ('Vip 2', 200000, None, 46, 9.20, 26, True),
        ('Vip 3', 300000, None, 44, 8.80, 36, True),
        ('Vip 4', 400000, None, 42, 8.40, 46, True),
        ('Vip 5', 500000, None, 40, 8.00, 56, True),
        ('Dimond', 800000, None, 38, 7.60, 66, True),
        ('Platinium', 1000000, None, 36, 7.20, 76, True),
    ]
    for level, min_amt, max_amt, fee, pct, slot, is_new in new_tiers:
        MembershipMaster.objects.update_or_create(
            level=level,
            is_new_plan=is_new,
            defaults={
                'min_amount': min_amt,
                'max_amount': max_amt,
                'service_fee': fee,
                'service_fee_percent': pct,
                'daily_slot': slot,
            }
        )

def remove_new_memberships(apps, schema_editor):
    MembershipMaster = apps.get_model('customer_wallet', 'MembershipMaster')
    MembershipMaster.objects.filter(is_new_plan=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0010_customerdemowallet_stop_loss_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmaster',
            name='is_new_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membershipmaster',
            name='level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master Gold', 'Master Gold'), ('Vip 1', 'Vip 1'), ('Vip 2', 'Vip 2'), ('Vip 3', 'Vip 3'), ('Vip 4', 'Vip 4'), ('Vip 5', 'Vip 5'), ('Dimond', 'Dimond'), ('Platinium', 'Platinium')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='membershipmaster',
            unique_together={('level', 'is_new_plan')},
        ),
        migrations.RunPython(populate_new_memberships, reverse_code=remove_new_memberships),
    ]
