# Generated by Django 4.1.13 on 2026-07-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet', '0011_membershipmaster_is_new_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletmanualdebit',
            name='is_offline_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
